spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/sell?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true
  jpa:
    show-sql: true  #打印SQL语句
    #如果为null就不显示
  jackson:
   default-property-inclusion: non_null

  freemarker:
    template-loader-path: classpath:/templates/  # classpath:  一定不能漏写
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: req
    suffix: .ftl

  redis:
    host: 192.168.56.101
    port: 6379

server:
  servlet:
    context-path: /sell




logging:
  pattern:
    console: "%d - %msg%n"  #日志输出的格式   %d日期  %msg日志信息  %n换行
  file:
    path: D:\Javaprojects\sellLog\     #配置文件的输出位置
  level:
    root: info          #全局
    #com.imooc.logTest: error   #在指定包的生效级别


#mpAppId: wx297ad305157e338b
  #  mpAppSecret: 00fde467df048493dc1739b4cf1ca2fb

wechat:
  mpAppId: wx297ad305157e338b
  mpAppSecret: 00fde467df048493dc1739b4cf1ca2fb
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: D:\Javaprojects\sell\var\h5.p12
  notifyUrl: http://lzxstudy.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: sRNFkuekQn6FWwS5uaqfyABSNqWLcNmDR9OpCOw8TnM  #订单状态更新通知

projectUrl:
  wechatMpAuthorize: http://lzxstudy.natapp1.cc
  wechatOpenAuthorize:  http://lzxstudy.natapp1.cc
  sell: http://lzxstudy.natapp1.cc